dropout: 0.2
lr: 0.02
model:
  model_args:
    d: 128
    final_reducer: mean
    lstm: standard
    mlp_transfer_fn: relu
    n_msg_layers: 3
    n_rounds: 10
    n_vote_layers: 3
  model_class: !!python/name:models.neurosat_architecture.NeuroSAT ''
n_classes: 2
n_features: 5
n_hidden: 32
selsam: true
weight_decay: 1.0e-10
