dropout: 0.2
lr: 0.0005
model:
  model_args:
    adj_orig: null
    kappa: 0.97
    n_layers: null
    num_node: null
  model_class: !!python/name:models.IGNN.IGNN ''
n_classes: 2
n_features: 5
n_hidden: 32
weight_decay: 0.0005
